---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2004-ansible}
    command: "pip3 install dnspython && /usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
test_sequence:
  - lint
  - destroy
  - dependency
  - syntax
  - create
  - converge
  - verify
  - destroy
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vaulturl: vault.local.at
        mail: test@test.at
lint: |
  yamllint .
  ansible-lint
  flake8
verifier:
  name: ansible
