#looping skript
- name: Get {{item}} systemd result
  shell: systemd-analyze security {{item}}
  register: analzye

- name: parse {{item}} analyze result first one
  set_fact:
    # convert the stdout lines to list, get the last line (result), split it on : and then get the second half, then split by space
    result_tmp: "{{(analzye.stdout_lines| list) | last | split(':') | last | split(' ')}}"

- name: parse {{item}} analyze result second one
  set_fact:
    #get the second part (number)
    result_number: "{{result_tmp [1] }}" 

- name: assert that consul service is under 7.0
  assert:
    that:
      - (result_number | float) <= 7
      - (result_number | float) >= 0
    fail_msg: "score of {{ item }} must be lower than 7.0. Reality: {{result_number}}"
    success_msg: "score of {{ item }} is lower than 7. Reality: {{result_number}}"