- name: Import and add Hashicorp key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add specified hashicorp repository into sources list
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  register: add_repository_consul

- name: update package cache (debian, etc)
  apt:
    update_cache: yes
  when: add_repository_consul.changed
  
- name: install consul
  apt:
    name: consul
    state: present
  register: consul

- name: copy the consul.service file
  copy:
    src: "{{ role_path }}/files/consul.service"
    dest: /etc/systemd/system/consul.service
  register: consulservice


- name: copy the ui.json file
  template:
    src: ui.j2
    dest: /etc/consul.d/ui.json
  register: consul_uijson
  
- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes
  when: consul.changed or consulservice.changed or consul_uijson.changed

- name: Make sure consul is running
  systemd:
    name: consul
    state: started
    

- name: Enable consul
  systemd:
    name: consul
    state: restarted
    enabled: yes
