---
# tasks file for secretsmanager
- name: include consul yml
  include_tasks: consul.yml

- name: resolve dns entry
  set_fact:
    vaulturl_check:  "{{ lookup('community.general.dig', vaulturl)}}"

- name: Test for line of vaulturl in /etc/hosts
  shell: grep -c "{{vaulturl}}$" /etc/hosts || true
  register: test_grep_hosts
  when: vaulturl_check

- name: include certbot yml only if the provided dns entry points to a real IP (indicated by selfsigned=false)
  include_tasks: certbot.yml
  when: not test_grep_hosts

- name: include vault yml
  include_tasks: vault.yml