---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-docker.io/pycontribs/centos:8}
    pre_build_image: true
test_sequence:
  - lint
  - destroy
  - dependency
  - syntax
  - create
  - converge
  - verify
  - destroy
provisioner:
  name: ansible
lint: |
  yamllint .
  ansible-lint
  flake8
verifier:
  name: ansible
