---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cicdtools-instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2004-ansible}
    pre_build_image: true
test_sequence:
  - lint
  - destroy
  - dependency
  - syntax
  - create
  - converge
  - verify
  - destroy
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        user: root
        bashrc_dir: "/root"
lint: |
  yamllint .
  ansible-lint
  flake8
verifier:
  name: ansible
