name: test ansible-role

on:
  push:
    paths:
      - 'suid-sgid-checker/**'
      - '.github/workflows/suid-sgid-buildtest.yml'
  pull_request:
    paths:
      - 'suid-sgid-checker/**'
      - '.github/workflows/suid-sgid-buildtest.yml'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Debug
        run: |
          echo "${{ github.repository }}"
      - name: molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: lint
          molecule_working_dir: suid-sgid-checker

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distros:
          - docker.io/pycontribs/centos:8
          - docker.io/pycontribs/alpine
          - docker.io/pycontribs/debian
          - docker.io/pycontribs/fedora
          - docker.io/pycontribs/opensuse
          - docker.io/pycontribs/ubuntu

    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: suid-sgid-checker
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distros }}