---
# tasks file for suid-sgid-checker
- name: find suid files
  become: true
  failed_when: false
  changed_when: false
  register: suid_files
  shell: |
    find / -user root -perm -4000 2>/dev/null

- name: find sgid files
  become: true
  failed_when: false
  changed_when: false
  register: sgid_files
  shell: |
    find / -user root -perm -2000 2>/dev/null

- name: Loop over suid stdout_lines
  include_tasks: check_indices_suid.yml
  loop: "{{ suid_files.stdout_lines }}"
  when: suid_files != []

- name: Loop over sgid stdout_lines
  include_tasks: check_indices_sgid.yml
  loop: "{{ sgid_files.stdout_lines }}"
  when: sgid_files != []